### ISSUE TITLE
Invalid players still take parcel

### ISSUE THREAD

**Issue by Entropy159** [borisshoes/fabric-mail#1]
I tried sending a parcel to a player on my server, but it said that the recipient doesn't exist and took my stack anyways. I tried looking through the files of the world and couldn't find the mail data anywhere to see if it actually sent or not. I checked the logs and it didn't say anything.
Edit: Turns out I sent it to the wrong username, but it still took my item stack. Is this intentional?

**Comment by borisshoes** [comment]
It shouldn't take the stack if it is sent to an invalid username. Thanks for reporting the bug!
I'll see if I can get a fix out for it in the next day or so.

**Comment by Entropy159** [comment]
I think it has to do with lines 208-209 in FabricMail.java - it's before the valid player check and it removes the stack even though the stack gets removed again in line 222.

**Comment by borisshoes** [comment]
Now fixed in version 1.4.
