### ISSUE TITLE
Broadcast and Airdrop commands seem broken

### ISSUE THREAD

**Issue by Tender-Paw** [borisshoes/fabric-mail#2]
The airdrop and broadcast commands always result in "An unexpected error has occurred while trying to execute that command".
So far I've tested it on a 1.21 server with fabric 16 and 16.3, with and without other mods present, and connecting with both modded and vanilla clients so it doesn't seem to be any sort of a mod conflict.

It is a shame these functions don't do work because they could be super useful with server announcements even when players are offline.

**Comment by borisshoes** [comment]
Thanks for the report! I will have a fix for it out tomorrow.

**Comment by borisshoes** [comment]
Issue is now fixed in the latest version
